version: '3.9'

services:

  servico-triagem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthsys-servico-triagem
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: triagem_db
      DB_USER: healthsys
      DB_PASS: healthsys
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthsys-network-pacientes
      - healthsys-network-gateway
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 10 && java -jar app.jar"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:16-alpine
    container_name: healthsys-postgres-triagem
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: triagem_db
      POSTGRES_USER: healthsys
      POSTGRES_PASSWORD: healthsys
    volumes:
      - postgres-triagem-data:/var/lib/postgresql/data
    networks:
      - healthsys-network-pacientes
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthsys -d triagem_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-triagem-data:
    driver: local

networks:
  healthsys-network-pacientes:
    external: true

  healthsys-network-gateway:
    external: true